services:
  mynginx:
    build: .

  web:
    image: nginx
    volumes:
      - ./nginx2/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
  # environment:
  #  - NGINX_HOST=foobar.com
  #  - NGINX_PORT=80